// Напишите функцию, которая принимает пол пользователя и возвращает объект данных 
// о пользователе сгенерированных случайно. Имена выбирайте из заранее созданных 
// массивов разных имен размером не меньше 50 элементов для каждого пола.

// randUser('male') //{name:"Ivan", age : 77, gender:"male"}
// randUser('female') //{name:"Inna", age : 3, gender:"female"}

let users = [[{name:"Gary Gutierrez", age : 25, gender:"male"},
            {name:"Mark Smith", age : 37, gender:"male"},
            {name:"Fernando Rowe", age : 29, gender:"male"},
            {name:"Phillip Wade", age : 62, gender:"male"},
            {name:"Thomas Nunez", age : 51, gender:"male"},
            {name:"Robert Tucker", age : 17, gender:"male"},
            {name:"Thomas Grant", age : 32, gender:"male"},
            {name:"Kurt Davis", age : 22, gender:"male"},
            {name:"Robert Hall", age : 19, gender:"male"},
            {name:"Edward Olson", age : 37, gender:"male"},
            {name:"Kevin Klein", age : 21, gender:"male"},
            {name:"Dennis Franklin", age : 46, gender:"male"},
            {name:"Dan West", age : 49, gender:"male"},
            {name:"Jason Martinez", age : 36, gender:"male"},
            {name:"Richard Johnson", age : 62, gender:"male"},
            {name:"Larry Campbell", age : 38, gender:"male"},
            {name:"Jerome Burns", age : 18, gender:"male"},
            {name:"Daniel Hanson", age : 19, gender:"male"},
            {name:"Roland Frazier", age : 53, gender:"male"},
            {name:"Leon Brown", age : 45, gender:"male"},
            {name:"David Scott", age : 34, gender:"male"},
            {name:"Walter Tucker", age : 66, gender:"male"},
            {name:"Russell Perez", age : 60, gender:"male"},
            {name:"Sidney Warren", age : 58, gender:"male"},
            {name:"William Johnson", age : 17, gender:"male"},
            {name:"Keith Blake", age : 47, gender:"male"},
            {name:"Steven Turner", age : 23, gender:"male"},
            {name:"Daniel Boyd", age : 36, gender:"male"},
            {name:"Brandon Wagner", age : 24, gender:"male"},
            {name:"Norman Farmer", age : 18, gender:"male"},
            {name:"Eddie Barnes", age : 69, gender:"male"},
            {name:"Keith Carson", age : 55, gender:"male"},
            {name:"Adam Mathis", age : 59, gender:"male"},
            {name:"Juan George", age : 70, gender:"male"},
            {name:"William Snyder", age : 37, gender:"male"},
            {name:"James Morris", age : 55, gender:"male"},
            {name:"William Dixon", age : 40, gender:"male"},
            {name:"Tom Davis", age : 31, gender:"male"},
            {name:"Maurice Sanchez", age : 26, gender:"male"},
            {name:"Matthew Reeves", age : 20, gender:"male"},
            {name:"Matthew Woods", age : 32, gender:"male"},
            {name:"David Gonzales", age : 57, gender:"male"},
            {name:"Donald Little", age : 46, gender:"male"},
            {name:"Matthew Simpson", age : 19, gender:"male"},
            {name:"Kenneth Garcia", age : 64, gender:"male"},
            {name:"Willie Baker", age : 73, gender:"male"},
            {name:"Joseph Snyder", age : 43, gender:"male"},
            {name:"Ricky Matthews", age : 38, gender:"male"},
            {name:"Jason Foster", age : 47, gender:"male"},
            {name:"Floyd Morgan", age : 29, gender:"male"},],

            [{name:"Lisa Gonzales", age : 25, gender:"female"},
            {name:"Clara Smith", age : 37, gender:"female"},
            {name:"Kristin Wilson", age : 29, gender:"female"},
            {name:"Hilda Chavez", age : 62, gender:"female"},
            {name:"Ida Sanders", age : 51, gender:"female"},
            {name:"Marcia Alexander", age : 17, gender:"female"},
            {name:"Rita Jones", age : 32, gender:"female"},
            {name:"Ruth Stewart", age : 22, gender:"female"},
            {name:"Amy Wheeler", age : 19, gender:"female"},
            {name:"Annie Fuller", age : 37, gender:"female"},
            {name:"Mary Nelson", age : 21, gender:"female"},
            {name:"Priscilla Johnson", age : 46, gender:"female"},
            {name:"Clara Brown", age : 49, gender:"female"},
            {name:"Catherine Stephens", age : 36, gender:"female"},
            {name:"Sarah Lane", age : 62, gender:"female"},
            {name:"Brenda Smith", age : 38, gender:"female"},
            {name:"Sheila Barber", age : 18, gender:"female"},
            {name:"Connie Hardy", age : 19, gender:"female"},
            {name:"Tonya Manning", age : 53, gender:"female"},
            {name:"Eva Alexander", age : 45, gender:"female"},
            {name:"Margaret Warren", age : 34, gender:"female"},
            {name:"Ruth Clarke", age : 66, gender:"female"},
            {name:"Amy Rodriguez", age : 60, gender:"female"},
            {name:"Ashley Robinson", age : 58, gender:"female"},
            {name:"Samantha Crawford", age : 17, gender:"female"},
            {name:"Christine Hicks", age : 27, gender:"female"},
            {name:"Deborah Smith", age : 43, gender:"female"},
            {name:"Carol Stevenson", age : 36, gender:"female"},
            {name:"Laura Davis", age : 24, gender:"female"},
            {name:"Barbara Barnett", age : 18, gender:"female"},
            {name:"Thelma Bowman", age : 69, gender:"female"},
            {name:"Sherry Allison", age : 55, gender:"female"},
            {name:"Angela Watson", age : 59, gender:"female"},
            {name:"Ann Stanley", age : 70, gender:"female"},
            {name:"Deborah Baldwin", age : 37, gender:"female"},
            {name:"Lori Pittman", age : 55, gender:"female"},
            {name:"Ethel Warren", age : 40, gender:"female"},
            {name:"Jeanne Brown", age : 31, gender:"female"},
            {name:"Theresa Payne", age : 26, gender:"female"},
            {name:"Margaret Davis", age : 20, gender:"female"},
            {name:"Diane Harris", age : 32, gender:"female"},
            {name:"Anna Sandoval", age : 57, gender:"female"},
            {name:"Sandra Moore", age : 46, gender:"female"},
            {name:"Kathryn Williams", age : 19, gender:"female"},
            {name:"Amanda Murray", age : 64, gender:"female"},
            {name:"Judy Adams", age : 73, gender:"female"},
            {name:"Barbara Williams", age : 43, gender:"female"},
            {name:"Angela Jacobs", age : 38, gender:"female"},
            {name:"Carrie Simmons", age : 47, gender:"female"},
            {name:"Phyllis Goodman", age : 29, gender:"female"},],];

            function randUser(item) { 
              if (item === users[0][0].gender) {
                  return users[0][Math.floor(Math.random() * users[0].length)];
              }
          
              if (item === users[1][1].gender) {
                  return users[1][Math.floor(Math.random() * users[1].length)];
              }
          }
          
          console.log(randUser("male"));
          console.log(randUser("female"));